<a href="https://colab.research.google.com/github/chaitanyakolicharamu/icp3_wek3/blob/main/ICP3a_venkat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Create random vector of size 15 with integers in range 1–20
a = np.random.randint(1, 21, size=15)
print("Original Array:")
print(a)


Original Array:
[ 4  5 14  4  2 16 15  1 11  9 13 13 20  3  4]


In [2]:
# Reshape to 3x5
a_reshaped = a.reshape(3, 5)
print("\nReshaped to 3x5:")
print(a_reshaped)




Reshaped to 3x5:
[[ 4  5 14  4  2]
 [16 15  1 11  9]
 [13 13 20  3  4]]


In [3]:
# Print shape
print("\nShape of reshaped array:", a_reshaped.shape)



Shape of reshaped array: (3, 5)


In [4]:
# Replace max in each row by 0
for i in range(a_reshaped.shape[0]):
    row_max_index = np.argmax(a_reshaped[i])
    a_reshaped[i, row_max_index] = 0

print("\nArray after replacing max in each row with 0:")
print(a_reshaped)



Array after replacing max in each row with 0:
[[ 4  5  0  4  2]
 [ 0 15  1 11  9]
 [13 13  0  3  4]]


In [ ]:
Part b – 4x3 Array with 4-byte Integers

In [5]:
# Create 2D array of shape 4x3 with 4-byte integers
b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12]], dtype=np.int32)

print("2D Array (4x3):")
print(b)
print("Shape:", b.shape)
print("Type:", type(b))
print("Data type:", b.dtype)


2D Array (4x3):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Shape: (4, 3)
Type: <class 'numpy.ndarray'>
Data type: int32


Part c – Eigenvalues and Eigenvectors

In [6]:
# Compute eigenvalues and right eigenvectors
c = np.array([[3, -2],
              [1,  0]])
eigenvalues, eigenvectors = np.linalg.eig(c)

print("Eigenvalues:")
print(eigenvalues)
print("Right Eigenvectors:")
print(eigenvectors)


Eigenvalues:
[2. 1.]
Right Eigenvectors:
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


Part d – Sum of Diagonal Elements

In [7]:
# Compute sum of diagonal elements
d = np.array([[0, 1, 2],
              [3, 4, 5]])
diag_sum = np.trace(d)

print("Sum of diagonal elements:")
print(diag_sum)


Sum of diagonal elements:
4


Part e – Reshape Without Changing Data

In [8]:
# Reshape 3x2 to 2x3 without changing data
e = np.array([[1, 2],
              [3, 4],
              [5, 6]])
reshaped_e = e.reshape(2, 3)

print("Original 3x2 Array:")
print(e)
print("Reshaped to 2x3:")
print(reshaped_e)


Original 3x2 Array:
[[1 2]
 [3 4]
 [5 6]]
Reshaped to 2x3:
[[1 2 3]
 [4 5 6]]
